import {Inter, Kosugi_Maru, Zen_Kaku_Gothic_New} from "next/font/google";
import "./globals.css";
import { AuthProvider } from './context/AuthProvider';

const inter = Inter({ subsets: ["latin"] });
const zenKakuGothNew = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});

export const metadata = {
  title: "PRETTI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zenKakuGothNew.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
